service: github-workflow-hook

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-west-2

plugins:
  - serverless-offline
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'